"""add massnahmen_typ, massnahme tables, seed default Massnahmen-Katalog

Revision ID: 00e96fea061a
Revises: 63cf7c163a7c
Create Date: 2026-07-26 17:11:39.897410

"""
from alembic import op
import sqlalchemy as sa


revision = '00e96fea061a'
down_revision = '63cf7c163a7c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('massnahmen_typ',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('setzt_zaehler_zurueck', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('massnahme',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('schueler_id', sa.Integer(), nullable=False),
    sa.Column('massnahmen_typ_id', sa.Integer(), nullable=False),
    sa.Column('datum', sa.Date(), nullable=False),
    sa.Column('notiz', sa.String(length=1000), nullable=True),
    sa.Column('erfasst_von_nutzer_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['erfasst_von_nutzer_id'], ['nutzer.id'], ),
    sa.ForeignKeyConstraint(['massnahmen_typ_id'], ['massnahmen_typ.id'], ),
    sa.ForeignKeyConstraint(['schueler_id'], ['schueler.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('massnahmen_typ_regel',
    sa.Column('massnahmen_typ_id', sa.Integer(), nullable=False),
    sa.Column('regel_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['massnahmen_typ_id'], ['massnahmen_typ.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['regel_id'], ['schwellwert_regel.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('massnahmen_typ_id', 'regel_id')
    )
    # ### end Alembic commands ###

    massnahmen_typ_table = sa.table(
        "massnahmen_typ",
        sa.column("id", sa.Integer),
        sa.column("name", sa.String),
        sa.column("setzt_zaehler_zurueck", sa.Boolean),
    )
    op.bulk_insert(
        massnahmen_typ_table,
        [
            {"name": "Gespräch", "setzt_zaehler_zurueck": False},
            {"name": "Elterngespräch", "setzt_zaehler_zurueck": False},
            {"name": "Nachsitzen", "setzt_zaehler_zurueck": True},
            {"name": "4h Nachsitzen", "setzt_zaehler_zurueck": True},
            {"name": "Schulverweis", "setzt_zaehler_zurueck": True},
            {"name": "Bußgeld", "setzt_zaehler_zurueck": True},
            {"name": "Zwangsgeld", "setzt_zaehler_zurueck": True},
        ],
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DELETE FROM massnahmen_typ")
    op.drop_table('massnahmen_typ_regel')
    op.drop_table('massnahme')
    op.drop_table('massnahmen_typ')
    # ### end Alembic commands ###
