"""add einstellung, audit_log tables

Revision ID: 0119b4ca676d
Revises: dda5794596ca
Create Date: 2026-07-24 12:46:49.950956

"""
from alembic import op
import sqlalchemy as sa


revision = '0119b4ca676d'
down_revision = 'dda5794596ca'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('aktion', sa.String(length=100), nullable=False),
    sa.Column('resource_typ', sa.String(length=50), nullable=False),
    sa.Column('resource_id', sa.String(length=50), nullable=True),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('zeitpunkt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('einstellung',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sync_interval_cron', sa.String(length=50), nullable=False),
    sa.Column('schuljahr_start_cache', sa.Date(), nullable=True),
    sa.Column('initialer_import_abgeschlossen', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('einstellung')
    op.drop_table('audit_log')
    # ### end Alembic commands ###
