"""add abteilung table, klasse.abteilung_id, drop klasse.stufe/schulart

Revision ID: 298476c1ab45
Revises: 56b9f8aed3f4
Create Date: 2026-07-26 10:15:00.000000

"""
from alembic import op
import sqlalchemy as sa


revision = '298476c1ab45'
down_revision = '56b9f8aed3f4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('abteilung',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('webuntis_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('long_name', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_abteilung_webuntis_id'), 'abteilung', ['webuntis_id'], unique=True)
    op.add_column('klasse', sa.Column('abteilung_id', sa.Integer(), nullable=True))
    op.create_foreign_key('klasse_abteilung_id_fkey', 'klasse', 'abteilung', ['abteilung_id'], ['id'])
    op.drop_column('klasse', 'stufe')
    op.drop_column('klasse', 'schulart')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('klasse', sa.Column('schulart', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('klasse', sa.Column('stufe', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.drop_constraint('klasse_abteilung_id_fkey', 'klasse', type_='foreignkey')
    op.drop_column('klasse', 'abteilung_id')
    op.drop_index(op.f('ix_abteilung_webuntis_id'), table_name='abteilung')
    op.drop_table('abteilung')
    # ### end Alembic commands ###
