"""add benachrichtigung table

Revision ID: 37bd5af171d6
Revises: 00e96fea061a
Create Date: 2026-07-26 17:26:48.976563

"""
from alembic import op
import sqlalchemy as sa


revision = '37bd5af171d6'
down_revision = '00e96fea061a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('benachrichtigung',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('schueler_id', sa.Integer(), nullable=False),
    sa.Column('regel_id', sa.Integer(), nullable=False),
    sa.Column('stufe_nr', sa.Integer(), nullable=False),
    sa.Column('gesendet_am', sa.DateTime(timezone=True), nullable=False),
    sa.Column('empfaenger', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['regel_id'], ['schwellwert_regel.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['schueler_id'], ['schueler.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('benachrichtigung')
    # ### end Alembic commands ###
