"""replace schueler webuntis_id/webuntis_key with externe_id, add einstellung.asv_csv_zuletzt_importiert_mtime

Revision ID: 3f726ec70da1
Revises: ce9c35768e75
Create Date: 2026-07-25 20:38:31.116262

"""
from alembic import op
import sqlalchemy as sa


revision = '3f726ec70da1'
down_revision = 'ce9c35768e75'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('einstellung', sa.Column('asv_csv_zuletzt_importiert_mtime', sa.DateTime(timezone=True), nullable=True))
    op.add_column('schueler', sa.Column('externe_id', sa.String(length=64), nullable=False))
    op.drop_index(op.f('ix_schueler_webuntis_id'), table_name='schueler')
    op.create_index(op.f('ix_schueler_externe_id'), 'schueler', ['externe_id'], unique=True)
    op.drop_column('schueler', 'webuntis_id')
    op.drop_column('schueler', 'webuntis_key')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('schueler', sa.Column('webuntis_key', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('schueler', sa.Column('webuntis_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_schueler_externe_id'), table_name='schueler')
    op.create_index(op.f('ix_schueler_webuntis_id'), 'schueler', ['webuntis_id'], unique=True)
    op.drop_column('schueler', 'externe_id')
    op.drop_column('einstellung', 'asv_csv_zuletzt_importiert_mtime')
    # ### end Alembic commands ###
