"""add benachrichtigung schueler_id and regel_id indexes

Revision ID: 43e3780702ba
Revises: fb5871c3593e
Create Date: 2026-07-26 19:29:53.728920

"""
from alembic import op
import sqlalchemy as sa


revision = '43e3780702ba'
down_revision = 'fb5871c3593e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_benachrichtigung_regel_id'), 'benachrichtigung', ['regel_id'], unique=False)
    op.create_index(op.f('ix_benachrichtigung_schueler_id'), 'benachrichtigung', ['schueler_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_benachrichtigung_schueler_id'), table_name='benachrichtigung')
    op.drop_index(op.f('ix_benachrichtigung_regel_id'), table_name='benachrichtigung')
    # ### end Alembic commands ###
