"""add einstellung.letzter_sync_am

Revision ID: 56b9f8aed3f4
Revises: 3f726ec70da1
Create Date: 2026-07-25 20:54:53.142554

"""
from alembic import op
import sqlalchemy as sa


revision = '56b9f8aed3f4'
down_revision = '3f726ec70da1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('einstellung', sa.Column('letzter_sync_am', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('einstellung', 'letzter_sync_am')
    # ### end Alembic commands ###
