"""add ausnahme table

Revision ID: 63cf7c163a7c
Revises: 93ee9ad459e1
Create Date: 2026-07-26 17:00:29.973869

"""
from alembic import op
import sqlalchemy as sa


revision = '63cf7c163a7c'
down_revision = '93ee9ad459e1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ausnahme',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('schueler_id', sa.Integer(), nullable=False),
    sa.Column('kategorie', sa.String(length=20), nullable=False),
    sa.Column('grund', sa.String(length=500), nullable=False),
    sa.Column('gueltig_bis', sa.Date(), nullable=True),
    sa.Column('aktiv', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['schueler_id'], ['schueler.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ausnahme')
    # ### end Alembic commands ###
