"""add schwellwert_regel, schwellwert_stufe tables

Revision ID: 89bcc97408e3
Revises: 298476c1ab45
Create Date: 2026-07-26 10:19:59.850549

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = '89bcc97408e3'
down_revision = '298476c1ab45'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('schwellwert_regel',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('typ', sa.String(length=20), nullable=False),
    sa.Column('geltungsbereich', sa.String(length=20), nullable=False),
    sa.Column('abteilung_id', sa.Integer(), nullable=True),
    sa.Column('klasse_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['abteilung_id'], ['abteilung.id'], ),
    sa.ForeignKeyConstraint(['klasse_id'], ['klasse.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('uq_schwellwert_regel_abteilung', 'schwellwert_regel', ['typ', 'abteilung_id'], unique=True, postgresql_where=sa.text('abteilung_id IS NOT NULL'))
    op.create_index('uq_schwellwert_regel_klasse', 'schwellwert_regel', ['typ', 'klasse_id'], unique=True, postgresql_where=sa.text('klasse_id IS NOT NULL'))
    op.create_index('uq_schwellwert_regel_schulweit', 'schwellwert_regel', ['typ'], unique=True, postgresql_where=sa.text("geltungsbereich = 'schulweit'"))
    op.create_table('schwellwert_stufe',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('regel_id', sa.Integer(), nullable=False),
    sa.Column('stufe_nr', sa.Integer(), nullable=False),
    sa.Column('einheit', sa.String(length=20), nullable=True),
    sa.Column('schwellenwert', sa.Integer(), nullable=False),
    sa.Column('fehlzeiten_filter', sa.String(length=20), nullable=True),
    sa.Column('empfaenger_rollen', postgresql.ARRAY(sa.String(length=20)), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['regel_id'], ['schwellwert_regel.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('regel_id', 'stufe_nr', name='uq_schwellwert_stufe_regel_stufe_nr')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('schwellwert_stufe')
    op.drop_index('uq_schwellwert_regel_schulweit', table_name='schwellwert_regel', postgresql_where=sa.text("geltungsbereich = 'schulweit'"))
    op.drop_index('uq_schwellwert_regel_klasse', table_name='schwellwert_regel', postgresql_where=sa.text('klasse_id IS NOT NULL'))
    op.drop_index('uq_schwellwert_regel_abteilung', table_name='schwellwert_regel', postgresql_where=sa.text('abteilung_id IS NOT NULL'))
    op.drop_table('schwellwert_regel')
    # ### end Alembic commands ###
