"""add schueler_zaehlerstand table

Revision ID: 93ee9ad459e1
Revises: 89bcc97408e3
Create Date: 2026-07-26 10:29:42.614946

"""
from alembic import op
import sqlalchemy as sa


revision = '93ee9ad459e1'
down_revision = '89bcc97408e3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('schueler_zaehlerstand',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('schueler_id', sa.Integer(), nullable=False),
    sa.Column('typ', sa.String(length=20), nullable=False),
    sa.Column('regel_id', sa.Integer(), nullable=False),
    sa.Column('aktueller_stand', sa.Integer(), nullable=False),
    sa.Column('erreichte_stufe_nr', sa.Integer(), nullable=True),
    sa.Column('letzter_reset_am', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['regel_id'], ['schwellwert_regel.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['schueler_id'], ['schueler.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('schueler_id', 'typ', name='uq_schueler_zaehlerstand_schueler_typ')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('schueler_zaehlerstand')
    # ### end Alembic commands ###
