"""add klasse, bereich tables

Revision ID: ac2d1b702760
Revises: f607961f644c
Create Date: 2026-07-24 12:26:33.043689

"""
from alembic import op
import sqlalchemy as sa


revision = 'ac2d1b702760'
down_revision = 'f607961f644c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bereich',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('klasse',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('webuntis_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('stufe', sa.String(length=20), nullable=True),
    sa.Column('schulart', sa.String(length=50), nullable=True),
    sa.Column('webuntis_teacher1_id', sa.Integer(), nullable=True),
    sa.Column('webuntis_teacher2_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_klasse_webuntis_id'), 'klasse', ['webuntis_id'], unique=True)
    op.create_table('bereich_klasse',
    sa.Column('bereich_id', sa.Integer(), nullable=False),
    sa.Column('klasse_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['bereich_id'], ['bereich.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['klasse_id'], ['klasse.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('bereich_id', 'klasse_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bereich_klasse')
    op.drop_index(op.f('ix_klasse_webuntis_id'), table_name='klasse')
    op.drop_table('klasse')
    op.drop_table('bereich')
    # ### end Alembic commands ###
