"""add nutzer, nutzer_klasse, nutzer_bereich tables

Revision ID: ce9c35768e75
Revises: 0119b4ca676d
Create Date: 2026-07-24 12:51:56.448257

"""
from alembic import op
import sqlalchemy as sa


revision = 'ce9c35768e75'
down_revision = '0119b4ca676d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('nutzer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('wp_user_id', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=200), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('rolle', sa.String(length=20), nullable=False),
    sa.Column('webuntis_teacher_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('webuntis_teacher_id')
    )
    op.create_index(op.f('ix_nutzer_wp_user_id'), 'nutzer', ['wp_user_id'], unique=True)
    op.create_table('nutzer_bereich',
    sa.Column('nutzer_id', sa.Integer(), nullable=False),
    sa.Column('bereich_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['bereich_id'], ['bereich.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['nutzer_id'], ['nutzer.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('nutzer_id', 'bereich_id')
    )
    op.create_table('nutzer_klasse',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nutzer_id', sa.Integer(), nullable=False),
    sa.Column('klasse_id', sa.Integer(), nullable=False),
    sa.Column('quelle', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['klasse_id'], ['klasse.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['nutzer_id'], ['nutzer.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nutzer_id', 'klasse_id', 'quelle', name='uq_nutzer_klasse_quelle')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('nutzer_klasse')
    op.drop_table('nutzer_bereich')
    op.drop_index(op.f('ix_nutzer_wp_user_id'), table_name='nutzer')
    op.drop_table('nutzer')
    # ### end Alembic commands ###
