"""add excuse_status, schueler, fehlzeit tables

Revision ID: d9aba588fce8
Revises: ac2d1b702760
Create Date: 2026-07-24 12:31:44.090127

"""
from alembic import op
import sqlalchemy as sa


revision = 'd9aba588fce8'
down_revision = 'ac2d1b702760'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('excuse_status',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.Column('long_name', sa.String(length=100), nullable=True),
    sa.Column('zaehlt_als_entschuldigt', sa.Boolean(), nullable=False),
    sa.Column('aktiv', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('schueler',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('webuntis_id', sa.Integer(), nullable=False),
    sa.Column('webuntis_key', sa.String(length=50), nullable=True),
    sa.Column('vorname', sa.String(length=100), nullable=False),
    sa.Column('nachname', sa.String(length=100), nullable=False),
    sa.Column('klasse_id', sa.Integer(), nullable=True),
    sa.Column('aktiv', sa.Boolean(), nullable=False),
    sa.Column('klassenzuordnung_aktualisiert_am', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['klasse_id'], ['klasse.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_schueler_webuntis_id'), 'schueler', ['webuntis_id'], unique=True)
    op.create_table('fehlzeit',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('schueler_id', sa.Integer(), nullable=False),
    sa.Column('typ', sa.String(length=10), nullable=False),
    sa.Column('datum', sa.Date(), nullable=False),
    sa.Column('start_zeit', sa.Integer(), nullable=False),
    sa.Column('end_zeit', sa.Integer(), nullable=False),
    sa.Column('fach', sa.String(length=50), nullable=True),
    sa.Column('excuse_status_id', sa.Integer(), nullable=True),
    sa.Column('grund_text', sa.String(length=500), nullable=True),
    sa.Column('invalid', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['excuse_status_id'], ['excuse_status.id'], ),
    sa.ForeignKeyConstraint(['schueler_id'], ['schueler.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('schueler_id', 'datum', 'start_zeit', 'end_zeit', 'typ', name='uq_fehlzeit_identity')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('fehlzeit')
    op.drop_index(op.f('ix_schueler_webuntis_id'), table_name='schueler')
    op.drop_table('schueler')
    op.drop_table('excuse_status')
    # ### end Alembic commands ###
