"""add classreg_category, klassenbuch_eintrag tables

Revision ID: dda5794596ca
Revises: d9aba588fce8
Create Date: 2026-07-24 12:36:11.826860

"""
from alembic import op
import sqlalchemy as sa


revision = 'dda5794596ca'
down_revision = 'd9aba588fce8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('classreg_category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('webuntis_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('long_name', sa.String(length=200), nullable=True),
    sa.Column('group_name', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('webuntis_id')
    )
    op.create_table('klassenbuch_eintrag',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('webuntis_id', sa.Integer(), nullable=False),
    sa.Column('schueler_id', sa.Integer(), nullable=False),
    sa.Column('kategorie_id', sa.Integer(), nullable=False),
    sa.Column('datum', sa.Date(), nullable=False),
    sa.Column('text', sa.String(length=1000), nullable=True),
    sa.Column('lesson_id', sa.Integer(), nullable=True),
    sa.Column('erstellt_von_teacher_id', sa.Integer(), nullable=True),
    sa.Column('geaendert_von_teacher_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['kategorie_id'], ['classreg_category.id'], ),
    sa.ForeignKeyConstraint(['schueler_id'], ['schueler.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('webuntis_id')
    )
    op.create_index(op.f('ix_klassenbuch_eintrag_webuntis_id'), 'klassenbuch_eintrag', ['webuntis_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_klassenbuch_eintrag_webuntis_id'), table_name='klassenbuch_eintrag')
    op.drop_table('klassenbuch_eintrag')
    op.drop_table('classreg_category')
    # ### end Alembic commands ###
