"""baseline (no tables yet)

Revision ID: f607961f644c
Revises: 
Create Date: 2026-07-24 12:18:25.512434

"""
from alembic import op
import sqlalchemy as sa


revision = 'f607961f644c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
