"""set_null_regel_id_fks

Revision ID: fb5871c3593e
Revises: 37bd5af171d6
Create Date: 2026-07-26 18:05:27.775237

"""
from alembic import op
import sqlalchemy as sa


revision = 'fb5871c3593e'
down_revision = '37bd5af171d6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('benachrichtigung', 'regel_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint(op.f('benachrichtigung_regel_id_fkey'), 'benachrichtigung', type_='foreignkey')
    op.create_foreign_key(
        op.f('benachrichtigung_regel_id_fkey'),
        'benachrichtigung', 'schwellwert_regel', ['regel_id'], ['id'], ondelete='SET NULL'
    )
    op.alter_column('schueler_zaehlerstand', 'regel_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint(op.f('schueler_zaehlerstand_regel_id_fkey'), 'schueler_zaehlerstand', type_='foreignkey')
    op.create_foreign_key(
        op.f('schueler_zaehlerstand_regel_id_fkey'),
        'schueler_zaehlerstand', 'schwellwert_regel', ['regel_id'], ['id'], ondelete='SET NULL'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('schueler_zaehlerstand_regel_id_fkey'), 'schueler_zaehlerstand', type_='foreignkey')
    op.create_foreign_key(op.f('schueler_zaehlerstand_regel_id_fkey'), 'schueler_zaehlerstand', 'schwellwert_regel', ['regel_id'], ['id'], ondelete='CASCADE')
    op.alter_column('schueler_zaehlerstand', 'regel_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint(op.f('benachrichtigung_regel_id_fkey'), 'benachrichtigung', type_='foreignkey')
    op.create_foreign_key(op.f('benachrichtigung_regel_id_fkey'), 'benachrichtigung', 'schwellwert_regel', ['regel_id'], ['id'], ondelete='CASCADE')
    op.alter_column('benachrichtigung', 'regel_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
